config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  resources :users

  get 'session/new'

  get  'login'   => 'session#new'
  
  post 'login'   => 'session#create'
  
  get 'logout'  => 'session#destroy'

  get '/search', to: 'users#search'
  get '/searchresults', to: 'users#searchresults'

  get 'addimage' => 'users#newimage'

  post 'addimage' => 'users#addimage'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :username, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts

	has_attached_file :avatar, { styles: { 
		:medium => "300x300>", 
		:thumb => "100x100>" }, 
		:default_url => "/images/:style/missing.png" }
		validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	validates :email, presence: true, uniqueness: true
	validates :password, :length => { :minimum => 6 }
	validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title, :user_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	 def new
  end

  def create
  	result = User.all.where(
      email: params[:email], password: params[:password]).first
    if result
      session[:user_id] = result.id
      flash[:notice] = "You have logged in!"
      redirect_to user_path result
    else
      flash[:notice] = "Invalid login/password. Please try again."
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out."
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
  end

  def searchresults
    @query = params[:username]
    #todo -need to use ILIKE in postgres where strings are case sensitive
    @users = User.where("username LIKE ?", "%#{params[:username]}%")
  end

  # def newimage
  #   @newimage = 
  # end
  # def createimage
  #   params.require(:bison).permit()
  # end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HelloRails</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<h1 class="site_headline"><%= link_to "This Is The Best App", root_path %> </h1>
		<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
		<% end %>
		<nav>
			<div>
				<%= link_to "New Post", new_post_path %>
				<% if !current_user %>
				<%= link_to 'Sign Up', new_user_path %>
				<% end %>
				<%= link_to "See Users", users_path %>
				<%= link_to "See Posts", posts_path %>
				<%= link_to "Search", search_path %>
			</div>
		</nav>

		<%= yield %>



		<div>
			<% if current_user %>
			<p>
			<%= link_to "Log Out", logout_path %>
			<% end %>
			<% if !current_user %>
			<%= link_to "Log In", login_path %>
			<% end %>
			<% if current_user %>
			<%= link_to "Profile", current_user %></p>
			<% end %>
		</div>
		<footer>
		<div id="mainfooter">
		<p>All Rights Reserved - Troy Starwalt</p>
		</div>
		</footer>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Title</th>
      <th>User</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td id="set_width"><%= post.content %></td>
      <td><%= post.title %></td>
      <td><%= post.user.username %></td>
      <% if post.user.avatar_file_name.nil? %>
      <td>No Image<% else %><%= image_tag post.user.avatar.url(:thumbnail) %></td>
      <% end %>
      <td><%= link_to 'Go to Post', post %></td>
      <% if @current_user %>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Content:</strong>
	<%= @post.content %>
</p>

<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>

<p>
	<strong>User:</strong>
	<%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/session/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="user_forms">
    <%= form_tag login_path do %>
    <div id="email_login">
      <%= label_tag 'email' %> <br>
      <%= email_field_tag 'email', nil, placeholder: 'Email Address', class: "ses_input_area" %><br>
    </div>
    <div id="password_login">
      <%= label_tag 'password' %> <br>
      <%= password_field_tag :password, nil, class: 'ses_input_area' %>
    </div>
    <br>

    <%= submit_tag 'Go', class: "ses_submit_btn" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", new_user_path %></p>
  </div>	
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
    <p>Upload your avatar. <%= f.file_field :avatar %></p>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %> | <%= user.email %> | <%= user.password %></td>
      <td><%= link_to 'See Users Profile', user %></td>
      <% if @current_user %>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <% end %>
      <% if @current_user %>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/newimage.html.erb
<div id="imageuploadform">	
	<%= form_for @user, :url => user_path, :html => { :multipart => true } do |form| %>   
	<%= form.file_field :avatar %>
	<% end %>
</div>

app/views/users/search.html.erb
<%= form_tag('/searchresults', method: :get) do %>
	<%= label_tag 'username' %>
	<%= text_field_tag 'username' %>

	<%= submit_tag 'submit' %>
<% end %>

app/views/users/searchresults.html.erb
<p>Here are your search results for query: "<%= @query %>"</p>
<ol>
<% @users.each do |u| %>
	<li>
		<%= link_to("#{u.username} #{u.email}", user_path(u)) %>
	</li>
<% end %>
</ol>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>.</h1>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
	<strong>Your Avatar:</strong><% console %>
	<% if @user.avatar_file_name.nil? %>
	<div class="useravatar">
	<p>You should upload an avatar.</p>
	<% else %>
	<%= image_tag @user.avatar.url(:medium) %>
	</div>
	<% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>